//
// UserAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class UserAPI {
    /**
     Add a new user
     
     - parameter body: (body) User object that needs to be added 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func addUser(body: GeneratedUser, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        addUserWithRequestBuilder(body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Add a new user
     - POST /users
     - 
     
     - parameter body: (body) User object that needs to be added 

     - returns: RequestBuilder<Void> 
     */
    open class func addUserWithRequestBuilder(body: GeneratedUser) -> RequestBuilder<Void> {
        let path = "/users"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Find user by ID
     
     - parameter _id: (path) ID of user to return 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getUserById(_id: String, completion: @escaping ((_ data: GeneratedUser?,_ error: Error?) -> Void)) {
        getUserByIdWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Find user by ID
     - GET /users/{Id}
     - Returns a single user
     - examples: [{contentType=application/json, example={"empty": false}}]
     
     - parameter _id: (path) ID of user to return 

     - returns: RequestBuilder<User> 
     */
    open class func getUserByIdWithRequestBuilder(_id: String) -> RequestBuilder<GeneratedUser> {
        var path = "/users/{Id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{Id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<GeneratedUser>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
