//
// APICouch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct APICouch: Codable {

    public var _id: String?
    public var name: String?
    public var address: String?
    public var city: String?
    public var country: String?
    public var latitude: Double?
    public var longitude: Double?
    public var maxGuests: Int?
    public var _description: String?
    public var imageUrls: [String]?
    public var ratingAverage: Int?
    public var ratingCount: Int?
    public var user: APIUser?

    public init(_id: String?, name: String?, address: String?, city: String?, country: String?, latitude: Double?, longitude: Double?, maxGuests: Int?, _description: String?, imageUrls: [String]?, ratingAverage: Int?, ratingCount: Int?, user: APIUser?) {
        self._id = _id
        self.name = name
        self.address = address
        self.city = city
        self.country = country
        self.latitude = latitude
        self.longitude = longitude
        self.maxGuests = maxGuests
        self._description = _description
        self.imageUrls = imageUrls
        self.ratingAverage = ratingAverage
        self.ratingCount = ratingCount
        self.user = user
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case address
        case city
        case country
        case latitude
        case longitude
        case maxGuests
        case _description = "description"
        case imageUrls
        case ratingAverage
        case ratingCount
        case user
    }


}

