//
// APIRating.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct APIRating: Codable {

    public var _id: String?
    public var user: APIUser?
    public var couch: APICouch?
    public var value: Int?
    public var comment: String?

    public init(_id: String?, user: APIUser?, couch: APICouch?, value: Int?, comment: String?) {
        self._id = _id
        self.user = user
        self.couch = couch
        self.value = value
        self.comment = comment
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case user
        case couch
        case value
        case comment
    }


}

