//
// APIReservation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct APIReservation: Codable {

    public var _id: String?
    public var user: APIUser?
    public var couch: APICouch?
    public var guestsNum: Int?
    public var start: Date?
    public var end: Date?

    public init(_id: String?, user: APIUser?, couch: APICouch?, guestsNum: Int?, start: Date?, end: Date?) {
        self._id = _id
        self.user = user
        self.couch = couch
        self.guestsNum = guestsNum
        self.start = start
        self.end = end
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case user
        case couch
        case guestsNum
        case start
        case end
    }


}

