//
// Channel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Channel: Codable {

    public var _id: String?
    public var itemType: String?
    public var label: String?

    public init(_id: String?, itemType: String?, label: String?) {
        self._id = _id
        self.itemType = itemType
        self.label = label
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case itemType
        case label
    }


}

