//
// ConfigurationType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum ConfigurationType: String, Codable {
    case heating = "heating"
    case cooling = "cooling"
    case weatherwatcher = "weatherWatcher"
    case lock = "lock"
}
