//
// Rating.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GeneratedRating: Codable {

    public var _id: String?
    public var userId: String?
    public var couchId: String?
    public var value: Int?
    public var comment: String?

    public init(_id: String?, userId: String?, couchId: String?, value: Int?, comment: String?) {
        self._id = _id
        self.userId = userId
        self.couchId = couchId
        self.value = value
        self.comment = comment
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case userId
        case couchId
        case value
        case comment
    }


}

